### ISSUE TITLE
Creatting KCEFClient failing

### ISSUE THREAD

**Issue by dimaklekchyan** [DatL4g/KCEF#10]
OS: Mac M1 13.6.4 (22G513)
JDK: correto-17.0.10

When i try to create KCEFClient after successful initialization of KCEF an error occurs
```
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: 'void org.cef.browser.CefMessageRouter_N.N_Initialize(org.cef.browser.CefMessageRouter$CefMessageRouterConfig)'
	at org.cef.browser.CefMessageRouter_N.N_Initialize(Native Method)
	at org.cef.browser.CefMessageRouter_N.stateHasChanged(CefMessageRouter_N.java:30)
	at org.cef.CefApp.onInitialization(CefApp.java:213)
	at org.cef.browser.CefMessageRouter_N.<init>(CefMessageRouter_N.java:24)
	at org.cef.browser.CefMessageRouter.create(CefMessageRouter.java:212)
	at org.cef.browser.CefMessageRouter.create(CefMessageRouter.java:197)
```
It happens due to creating of CefMessageRouter in KCEFClient init block
```
val router = CefMessageRouter.create(
            CefMessageRouter.CefMessageRouterConfig("cefQueryEvaluate", "cefQueryEvaluateCancel")
)
```
but CefClient creating without  CefMessageRouter finishes successful

How to solve the problem?

**Comment by nsullivan251** [comment]
I was just experiencing this same issue. 
What worked for me was setting the JBR package to the previous release in the KCEF configuration builder.

`release("jbr-release-17.0.10b1087.23")`

**Comment by dimaklekchyan** [comment]
@nsullivan251 Thank you! It works
@DatL4g Sorry i missed the topic
